import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 28, y = 28 }
dynamic_padding = true
opacity = 0.95

[font]
normal = { family = "MesloLGS NF", style = "Regular" }

[cursor]
style = { shape = "Beam" }

